### ISSUE TITLE
@ character

### ISSUE THREAD

**Issue by vip32** [serilog/serilog-formatting-compact#12]
just curious: why are the properties prefixed with an @ character?

**Comment by nblumhardt** [comment]
Hi Vincent - good question!

`@` is prefixed so that the properties significant to the format (timestamp, message and so-on) have names that won't conflict with any valid identifier in C#, JavaScript, Java, C, C++, Rust and so-on.

Using `_` or `$` would still leave room for conflicts.

Using no prefix would work, but then some kind of disambiguation between a property called `t`, and the `t` timestamp property, would need to be conjured up.

`#`, `%`, `*` and so-on would also have worked, but `@` just happens to be nice and easy to reach one-handed on a US/QWERTY keyboard and doesn't usually have any other implied semantics, mathematical or otherwise.

`@` is also the character C# uses to escape keywords into identifiers, FWIW:

``` csharp
var @class = "Hello, world!"
```

**Comment by vip32** [comment]
hi Nicholas,
Thanks for explaining,
what are your ideas to make this configurable on the formatter? with a default of @. Does it makes sense and would you accept PR? that should also be taken care of in the [reader](https://github.com/nblumhardt/serilog-formatting-compact-reader)

my use case is that i need to store the json in [LiteDB](https://github.com/vip32/serilog-sinks-litedb) which currently has issues deserializing this @ json to bson. there are several ways to solve this (in my sink, or litedb itself), just figuring out what is best.

**Comment by nblumhardt** [comment]
Hi Vincent,

The aim in this repository is to represent the specific "compact JSON" format, rather than provide a general-purpose/configurable JSON serializer, so I don't think an optional escape character is on the roadmap. Keeping the code direct/tight also helps towards the faster performance that this library achieves vs. the earlier configurable formatter.

Would the `JsonFormatter` in _Serilog.dll_ be a better fit for your use case? It uses a different schema so that no escaping is necessary at all.

The actual formatter code here is only a [few dozen significant LOC](https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs) - copying and modifying is also a pretty reasonable option to consider.

Cheers,
Nick

**Comment by vip32** [comment]
totally agree. like you describe, i can handle this another way. thx for giving the insight.

**Comment by nblumhardt** [comment]
Great, let me know if you need a hand with any of it 👍
