### ISSUE TITLE
Informational log level gets removed from the logged json body

### ISSUE THREAD

**Issue by MichaConrad** [serilog/serilog-formatting-compact#13]
[Looks like it is intentional](https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs#L90)

My question is, why do you log the level for all levels except information?

I'm using the log output to populate an ES index which works great except for Info messages. And I'd have to treat info messages differently then anything else which is a little bit odd ;)

thanks,
m

**Comment by skomis-mm** [comment]
@MichaCo , i think it's optimization to minimize payload size since `Informational` level is most common

**Comment by MichaConrad** [comment]
@skomis-mm True. The thing is, when you consume or work with the logs, you usually expect a consistent format.
But hey, that's just my opinion ;)

That being said, I can fix it up later in the pipeline by mutating the json in logstash for example. 
Still, its one more thing to tweak..

**Comment by nblumhardt** [comment]
Well, the format _is_ consistent ;-) ... it's just that it takes the position that `Information` is semantically empty:

 * `Error` - the event represents an error
 * `Warning` - the event indicates a potential problem
 * `Debug` - the event is trivia for debugging
 * ...
 * `Information` - the event is ... an event carrying some information?

The exception `@x` is treated similarly: if there was no exception associated with an event, no exception property is included (we don't write `"@x": null`).

I can see the down-side, but I guess it is what it is at this point. Every format has some pros/cons; I'd rather in this case we accept them instead of adding switches, because every target is different: once we've been down that road, we'll have 100 different options to emit a format that's both universal and completely useless for interchange.

Hope this explains some of the thinking - thanks for raising the issue @MichaCo.

**Comment by Pzixel** [comment]
> I can see the down-side, but I guess it is what it is at this point. Every format has some pros/cons; I'd rather in this case we accept them instead of adding switches, because every target is different: once we've been down that road, we'll have 100 different options to emit a format that's both universal and completely useless for interchange.

I think there is a middle ground between "100 switches" and "no switches at all". Currently library implementation is more like snippet for a copy-paste-and-edit rather than library. Hope you will reconsider your position.

**Comment by nblumhardt** [comment]
Thanks for the feedback @Pzixel - yes, being a simple copy-pastable example is very much a goal, here. It means no one is blocked - the code is simple enough for just about anyone to modify, in any arbitrary way - and yet, four years after releasing this, the code is as fresh, efficient, and legacy-free as can be :-)

We've been down the configurable formatting road before and when writing this this particular library and format, I decided to try the alternative opinionated-but-easy-to-copy-paste approach, and so far it's worked well. There's definitely a role for configurable formatters, it's just that this library isn't supposed to be one.

For ultimately configurable JSON formatting, check out: https://github.com/serilog/serilog-expressions#formatting (still in development, feedback over there appreciated).
