### ISSUE TITLE
Change the timestamp format

### ISSUE THREAD

**Issue by artdedeco** [serilog/serilog-formatting-compact#18]
Is there a way to change the locale for the "@t" timestamp attribute?

**Comment by nblumhardt** [comment]
Hi Andre - no, the format's deliberately very prescriptive in this library. The `CompactJsonFormatter` class is very small, though - https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs - so copying it into your project to create a `LocalCompactJsonFormatter` should be a bearable workaround. Does that help?

Best regards,
Nick

**Comment by artdedeco** [comment]
Well, I would prefer to use the official nuget package to be honest 😝. Can't we consider making it configurable? I can try to help.

**Comment by nblumhardt** [comment]
Hi Andre! Thanks for the reply, I understand the preference, but we've made a conscious decision to avoid configurability in this package because a) it's the basis for something we want to be a general interchange format, and so stable/predictable, and b) because there are a nearly infinite variety of customization scenarios, and trying to cater to them all effectively killed our last JSON formatting codebase :-)
