### ISSUE TITLE
Force Log level to be written

### ISSUE THREAD

**Issue by tugberkugurlu** [serilog/serilog-formatting-compact#19]
I can see that `@l` is written only for non-info cases, [judging from the README](https://github.com/serilog/serilog-formatting-compact/tree/7551ea128eb09a081d13bf3615f4198e0209a6ce#reified-properties):

![image](https://user-images.githubusercontent.com/328122/38813469-e81e879c-4186-11e8-8a7b-91f68e030381.png)

I have a few issues:

 - `@l` seems to be not written for non-info cases as well (e.g. Error)
 - I want to enforce `@l` to be written in every case. Is that possible?

**Comment by nblumhardt** [comment]
Hi!

Is it possible that your "error" events have exceptions, but are otherwise at the info level? The level check is pretty simple: https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs#L90

Though adding `@l` in every case is reasonable, the goal of this package is to be as close to a standardized, canonical implementation of the formatting standard as possible. (There's some brief discussion of this request in particular in https://github.com/serilog/serilog-formatting-compact/issues/13#issuecomment-289149737).

The [`CompactJsonFormatter` class](https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs) is intended to be easily copy-pastable to make these kinds of tweaks - is that an option for you?

(A generic, general-purpose JSON formatting library for Serilog would also be a decent option - we haven't made any movement in that direction so far, though; it's just that this is not that library :-) .)

**Comment by tugberkugurlu** [comment]
that makes sense 👍 

> @l seems to be not written for non-info cases as well (e.g. Error)

Also, scratch this one. That was my bad 🤦‍♂️

**Comment by tugberkugurlu** [comment]
> the goal of this package is to be as close to a standardized, canonical implementation of the formatting standard as possible

Is this a known standard? Is there any docs on this somewhere?

**Comment by nblumhardt** [comment]
:+1:

Just an informal standard right now :-) The complete docs are in https://github.com/serilog/serilog-formatting-compact#format-details, currently - let me know if you spot any missing details.

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.

**Comment by zidad** [comment]
do you have an example of the expression template that would output the exact format of the CompactJsonFormatter?

**Comment by nblumhardt** [comment]
Hi @zidad; the template is:

```csharp
    .WriteTo.Console(new ExpressionTemplate(
        "{ {@t, @mt, @r, @l, @x, @sp, @tr, ..@p} }\n"))
```

If you want the rendered version:

 
```csharp
    .WriteTo.Console(new ExpressionTemplate(
        "{ {@t, @m, @i, @r, @l, @x, @sp, @tr, ..@p} }\n"))
```

HTH,
Nick

**Comment by zidad** [comment]
Ha, that's simpler than I thought it would be, many thanks I'll check it out!
