### ISSUE TITLE
Level field (@l) is not included when it's set to Information

### ISSUE THREAD

**Issue by tdabasinskas** [serilog/serilog-formatting-compact#20]
Hello,

As per the lines below, the log level is not included if it's set to `Informational`:

https://github.com/serilog/serilog-formatting-compact/blob/06e18e46e5c2e40feb6f880b8d420aec7677c274/src/Serilog.Formatting.Compact/Formatting/Compact/RenderedCompactJsonFormatter.cs#L73

I know the package is named `compact`, but the mentioned functionality is really not intuitive. Spent an hour or so to realize why events pushed to Graylog are missing the Log Level when using `RenderedCompactJsonFormatter`, yet, working OK when using [JsonFormatter](https://github.com/serilog/serilog/blob/master/src/Serilog/Formatting/Json/JsonFormatter.cs).

Would it be possible to to remove that condition?

**Comment by tdabasinskas** [comment]
Just noticed this is a documented behavior (https://github.com/serilog/serilog-formatting-compact#format-details) - my bad for missing that out.

Anyhow, seeing there were already similar issues for that (#19), I still believe the log level should be always included to avoid confusion. I'd say it's particularly relevant when viewing the events in external systems, such as Kibana or Graylog, as people viewing the logs there, might not have the knowledge about the empty LogLevel defaulting to `INFO`.

**Comment by nblumhardt** [comment]
Hi @TDabasinskas - thanks for the note :+1:

It's a reasonable suggestion, but as discussed on the other thread it's not a change we will make in this library.

When `CompactJsonFormatter` and the rendered variant were created, we moved most of the "interesting" code into `JsonValueFormatter`, leaving the outer "wrapper" formatters very simple so that the plethora of different JSON formatting requirements could be solved by copy/paste, rather than by us creating a configurable formatter (there are a lot of other possible variations out there :-)). So far this is working out well - sorry about the lost time trying to figure out the absence of the field, though, and let me know if you need a hand customizing the code to your requirements.

Best regards,
Nick

**Comment by nblumhardt** [comment]
(If anyone's decided to publish alternative formatter variants to NuGet to handle this case and others, by the way, please chime in here so that we can link them more prominently. Thanks!)

**Comment by nblumhardt** [comment]
Here's one for this purpose - though it's lacking docs unfortunately: https://www.nuget.org/packages/IchAtGithub.Serilog.Formatting.Compact/

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.

**Comment by zidad** [comment]
I don't really want to have to think about expression templates and just use the default, except I don't want informational log levels to be omitted, can we not just add a parameter to the RenderedCompactJsonFormatter.cs? Would such a PR be accepted?
