### ISSUE TITLE
compact json formatter @t overriding with utc +3

### ISSUE THREAD

**Issue by aburcuburcu** [serilog/serilog-formatting-compact#27]
hi,
l am using serilog compact json formatter in my project. And my logs always have utc datetime in @t info. l saw @t gives an İso 8601 timestamp. l should override it with utc+3 .  
is it possible? l should find anything.

Note: l try this , l used enricher and l got utc +3. but when i used compact json formatter, it remove timestamp utc+3 and gives again @t as iso 8601 timestamp. how can i override it? 
thanks.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note.

This particular project is very "opinionated" - just the one, fixed, format, and not really any configuration. It's intended to stay that way so that the core files, like this one:

https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs

can stay very small and focused. Most of the heavy lifting is done in Serilog's `JsonValueFormatter`. If you want to modify the way the formatter works, it's easy to copy just this file into your project and modify it however you would like.

Hope this helps,
Nick

**Comment by aburcuburcu** [comment]
Thank you, it worked.
