### ISSUE TITLE
How to add more properties with a `@` sigil?

### ISSUE THREAD

**Issue by uhfath** [serilog/serilog-formatting-compact#65]
Currently these are escaped during output:
https://github.com/serilog/serilog-formatting-compact/blob/efbbe3e2cdc783ec9c24221c07c2f1c490db077a/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs#L122-L126

We wanted to add some more properties to use with [Seq](https://docs.datalust.co/docs/posting-raw-events#reified-properties) but they are escaped.
Is there any way to get these working?
I know we could just fork the repo and make the change, but I was just wondering why this part is like this and if there are plans to add an option to turn off escaping.

**Comment by nblumhardt** [comment]
Hi! The SerilogTracing project provides some formatting helpers that might do what you're looking for. Otherwise, Serilog.Expressions handles all manner of custom JSON output with very little configuration; this post should cover it all: https://nblumhardt.com/2021/06/customize-serilog-json-output/ - HTH!

**Comment by uhfath** [comment]
@nblumhardt thanks for the link.
I've considered using `Serilog.Expressions` but wasn't sure it is capable of property transformations.
Will sure take a look.
